### ISSUE TITLE
i followed the guide but when i run "yarn run build" ,there are some warnings 

### ISSUE THREAD

**Issue by gtxgtgts** [SmartPhoenix/PK.js#3]
pkjs@VM-0-5-ubuntu:~/PK.js$ yarn run build
yarn run v1.21.1
$ cd server && npm run build && cd ../client && npm run build
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1582473655413-0.054039893461627964/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> server@1.0.0 build /home/pkjs/PK.js/server
> del-cli build && babel src -d build --copy-files

Successfully compiled 119 files with Babel.
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1582473655413-0.054039893461627964/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> client@1.0.0 build /home/pkjs/PK.js/client
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  262.76 KB  build/static/js/2.f9a6d5b6.chunk.js
  52.23 KB   build/static/css/main.8db67e0b.chunk.css
  31.28 KB   build/static/js/main.9d17ad85.chunk.js
  762 B      build/static/js/runtime~main.a8a9905a.js

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

Find out more about deployment here:

  https://bit.ly/CRA-deploy

Done in 40.73s.
pkjs@VM-0-5-ubuntu:~/PK.js$ serve -s build
ERROR: Cannot copy to clipboard: write EPIPE

   ┌────────────────────────────────────────────────┐
   │                                                │
   │   Serving!                                     │
   │                                                │
   │   - Local:            http://localhost:5000    │
   │   - On Your Network:  http://172.17.0.5:5000   │
   │                                                │
   └────────────────────────────────────────────────┘

* Connection closed *

**Comment by gtxgtgts** [comment]
i skipped and found i can only enter the home page and cannot login

**Comment by Thomas-Smyth** [comment]
Warnings are fine.

Sounds like you failed to follow the setup guide at some step. Please check that MongoDB is running and you set you SteamAPI key up correctly.
